# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys3_Constraints.xdc

# IP: ip/blk_mem_gen_15/blk_mem_gen_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_15 || ORIG_REF_NAME==blk_mem_gen_15}]

# IP: ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_7 || ORIG_REF_NAME==blk_mem_gen_7}]

# IP: ip/blk_mem_gen_6/blk_mem_gen_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_6 || ORIG_REF_NAME==blk_mem_gen_6}]

# XDC: ip/blk_mem_gen_15/blk_mem_gen_15_ooc.xdc

# XDC: ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc

# XDC: ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc
