# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.cache/wt [current_project]
set_property parent.project_path C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/AquaDragon/Desktop/KeyboardSampleCode/ip [current_project]
set_property ip_output_repo c:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/0.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/1.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/2.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/3.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/4.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/5.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/6.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/7.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/blank.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/8.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/9.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/10.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/11.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/12.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/13.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/14.coe
add_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Pictrans/15.coe
read_verilog -library xil_defaultlib {
  C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/imports/Downloads/clock_divider.v
  C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/imports/demo2/vga.v
  C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/new/VGAsetup.v
}
read_ip -quiet C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_15/blk_mem_gen_15.xci
set_property used_in_implementation false [get_files -all c:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_15/blk_mem_gen_15_ooc.xdc]
set_property is_locked true [get_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_15/blk_mem_gen_15.xci]

read_ip -quiet C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci
set_property used_in_implementation false [get_files -all c:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7_ooc.xdc]
set_property is_locked true [get_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_7/blk_mem_gen_7.xci]

read_ip -quiet C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci
set_property used_in_implementation false [get_files -all c:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6_ooc.xdc]
set_property is_locked true [get_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/sources_1/ip/blk_mem_gen_6/blk_mem_gen_6.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/constrs_1/imports/Downloads/Basys3_Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/AquaDragon/Desktop/Good_Game/Good_Game/Good_Game.srcs/constrs_1/imports/Downloads/Basys3_Constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top VGAsetup -part xc7a35tcpg236-1 -directive RuntimeOptimized -quick


write_checkpoint -force -noxdef VGAsetup.dcp

catch { report_utilization -file VGAsetup_utilization_synth.rpt -pb VGAsetup_utilization_synth.pb }
